-- 테이블, 뷰 삭제
DROP TABLE MEMBER_JOIN_INFO CASCADE CONSTRAINT;
DROP TABLE MEMBER_BODY_INFO CASCADE CONSTRAINT;
DROP TABLE MEMBER_BOARD CASCADE CONSTRAINT;
DROP SEQUENCE CGI_4_1220_4.MEMBER_BOARD_SEQ;

-- 테이블 생성
CREATE TABLE MEMBER_JOIN_INFO (
    ID VARCHAR2(50),
    PW VARCHAR2(64) NOT NULL,
    FULL_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    B_YEAR NUMBER(4) NOT NULL,
    B_MONTH NUMBER(2) NOT NULL,
    B_DAY NUMBER(2) NOT NULL,
    SEX NUMBER(1) NOT NULL,
    -- 제약 조건
    CONSTRAINT JOIN_PK PRIMARY KEY (ID)
);
CREATE TABLE MEMBER_BODY_INFO (
    /*
     비만도 계산할거면 줄 자를 사서 허리둘레랑 엉덩이둘레는 재야지
     키랑 몸무게만 쓸거면 그냥 계산기를 써
     그래서 NOT NULL이다.
     */
    ID VARCHAR2(50),
    HEIGHT VARCHAR2(64) NOT NULL,
    MASS VARCHAR2(64) NOT NULL,
    WAIST VARCHAR2(64) NOT NULL,
    HIP VARCHAR2(64) NOT NULL,
    UPLOAD DATE DEFAULT SYSDATE NOT NULL,
    -- 체질량 수치 정보는 서버에서 계산한 이후 DB에 저장
    BMI VARCHAR2(64) NOT NULL,
    RFM VARCHAR2(64) NOT NULL,
    BAI VARCHAR2(64) NOT NULL,
    WHR VARCHAR2(64) NOT NULL,
    WHTR VARCHAR2(64) NOT NULL,
    -- 제약 조건
    CONSTRAINT BODY_PK PRIMARY KEY (ID, UPLOAD),
    CONSTRAINT BODY_FK FOREIGN KEY (ID) REFERENCES MEMBER_JOIN_INFO (ID)
);

CREATE TABLE MEMBER_BOARD (
   B_NUM NUMBER,
    ID VARCHAR2(50),
    B_DATE DATE DEFAULT SYSDATE NOT NULL,
    B_TITLE VARCHAR2(150) NOT NULL,
    B_CONTENT VARCHAR2(1300) NOT NULL,
    B_NO NUMBER DEFAULT 0 NOT NULL,
    
    -- 제약 조건
    CONSTRAINT BOARD_PK PRIMARY KEY (B_NUM),
    CONSTRAINT BOARD_FK FOREIGN KEY (ID) REFERENCES MEMBER_JOIN_INFO(ID)
);


CREATE SEQUENCE CGI_4_1220_4.MEMBER_BOARD_SEQ
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   START WITH 1
   NOCACHE
   NOORDER
   NOCYCLE;

   
   
SELECT * FROM MEMBER_JOIN_INFO J FULL OUTER JOIN MEMBER_BODY_INFO B ON J.ID = B.ID WHERE J.ID = 'qkrtjdus' and J.PW = '4b6a8c32273e6516cbb7c0cfdc474eba7e49b6d5e3c6cf3e29984e6cb85a9bd3';
SELECT * FROM MEMBER_JOIN_INFO J FULL OUTER JOIN MEMBER_BODY_INFO B ON J.ID = B.ID WHERE J.ID = 'qkrtjdus' and J.PW = '3548';



-- 모든 신체정보 불러오기
SELECT *
FROM MEMBER_JOIN_INFO J RIGHT OUTER JOIN MEMBER_BODY_INFO B ON J.ID = B.ID
WHERE J.ID = 'qkrtjdus';



SELECT * FROM MEMBER_BODY_INFO WHERE ID = 'qkrtjdus';








select * from MEMBER_JOIN_INFO;
   
SELECT *
FROM MEMBER_JOIN_INFO
WHERE ID = 'qkrtjdus' AND PW = '4b6a8c32273e6516cbb7c0cfdc474eba7e49b6d5e3c6cf3e29984e6cb85a9bd3';
   
SELECT *
FROM MEMBER_JOIN_INFO
WHERE ID = 'qkrtjdus';
   

   





delete from MEMBER_JOIN_INFO
WHERE ID = 'qkrtjdus';

select * from MEMBER_BOARD;

select b_num, b_title, id, b_date from member_board where b_num < 2 order by b_num limit 10

delete from MEMBER_BOARD where id = 'yunje';








select * from member_board order by b_num DESC;

select * from member_board where b_num between 21 and 16 order by b_num DESC ;



SELECT *
FROM MEMBER_JOIN_INFO
WHERE ID = '123' or 1=1; -- AND PW = ?";






